// Active target countries (from "List of Countries.xlsx", 50 entries).
// Used as suggestions in AI Search and Add/Edit Company country fields.
export const COUNTRIES: string[] = [
  "Australia",
  "Austria",
  "Bahrain",
  "Belgium",
  "Bulgaria",
  "China",
  "Croatia",
  "Cyprus",
  "Denmark",
  "Estonia",
  "Finland",
  "France",
  "Germany",
  "Greece",
  "Hungary",
  "Iceland",
  "Indonesia",
  "Ireland",
  "Italy",
  "Japan",
  "Kuwait",
  "Latvia",
  "Libya",
  "Lithuania",
  "Luxembourg",
  "Malaysia",
  "Malta",
  "Netherlands",
  "New Zealand",
  "Norway",
  "Oman",
  "Philippines",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Romania",
  "Saudi Arabia",
  "Singapore",
  "Slovak Republic",
  "Slovenia",
  "South Korea",
  "Spain",
  "Sweden",
  "Switzerland",
  "Thailand",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
];
